spring:
  application:
    name: thesis-backend
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

security:
  jwt:
    token:
      secret-key: 1234

custom:
  avatar-directory: src/main/resources/static/avatars